version: '2'

services:
  nextcloudpi:
    image: schoeffm/rpi-nextcloud
    ports:
      - "4043:443"
      - "8088:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

nextcloud:
  image: schoeffm/rpi-nextcloud
  ports:
    - "8088:80"
    - "4043:443"
  links:
    - db:mysql
  volumes_from:
    - data 
  environment:
    OWNCLOUD_SERVERNAME: pibox
db:
  image: schoeffm/rpi-nextcloud-mysql
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: hypriot
    OWNCLOUD_DB_USER: admin
    OWNCLOUD_DB_PASSWORD: AdminAdmin
data:
  image: schoeffm/rpi-nextcloud-data
  environment:
    OWNCLOUD_DB_USER: admin
    OWNCLOUD_DB_PASSWORD: AdminAdmin